/**
 * Pure playoff-bracket math: P playoff teams -> weeks, byes, and a FIXED
 * single-elimination bracket. Hermetic (no DB, no Deno runtime APIs), unit-tested
 * exhaustively in playoff-bracket.test.ts.
 *
 * PRODUCT RULE (Giorgio, 2026-09-29): the commissioner picks any P from 2 to the
 * number of managers; everything else is derived here.
 *   weeks W      = ceil(log2 P)
 *   byes         = 2^W - P, given to the TOP seeds
 *   bracket      = FIXED (no re-seeding): the winner of (round r, position p)
 *                  always plays in (round r+1, position floor(p/2)), slot team1
 *                  when p is even and team2 when p is odd.
 *   A bye is an AUTO-ADVANCE: no game, no result, not a win, in no record.
 *
 * SLOT PLACEMENT. The 2^W bracket lines are filled in the display order the
 * design board draws (seed 1 at the top, seed 2 at the bottom):
 *   [1,2] -> each seed s at index i expands to [s, 2n+1-s] (i even) or
 *   [2n+1-s, s] (i odd), where 2n is the new line count.
 *     4:  1,4 | 3,2
 *     8:  1,8 | 5,4 | 3,6 | 7,2
 *     16: 1,16 | 9,8 | 5,12 | 13,4 | 3,14 | 11,6 | 7,10 | 15,2
 * This pairs teams IDENTICALLY to the textbook order (1,8,4,5,2,7,3,6: 1 meets
 * the 4/5 winner, 2 meets the 3/6 winner); only the vertical position differs.
 * The test file proves the two agree on every round's groupings for 2..64 lines.
 *
 * A round-1 line pair whose lower seed is > P is a BYE: the top seed has no
 * round-1 game and is placed straight into its round-2 slot. Because byes =
 * 2^W - P < 2^(W-1), every round 1 has at least one real game, and no seed ever
 * gets two byes.
 *
 * SLOT TABLE (round-1 games by position; byes as seed->round-2 position.slot):
 *   P=2 W1 b0  #0 1v2
 *   P=3 W2 b1  #1 2v3  | 1->R2#0.t1
 *   P=4 W2 b0  #0 1v4  #1 2v3
 *   P=5 W3 b3  #1 4v5  | 1->R2#0.t1  3->R2#1.t1  2->R2#1.t2
 *   P=6 W3 b2  #1 4v5  #2 3v6  | 1->R2#0.t1  2->R2#1.t2
 *   P=7 W3 b1  #1 4v5  #2 3v6  #3 2v7  | 1->R2#0.t1
 *   P=8 W3 b0  #0 1v8  #1 4v5  #2 3v6  #3 2v7
 *   P=9 W4 b7  #1 8v9  | 1->R2#0.t1  5->R2#1.t1  4->R2#1.t2  3->R2#2.t1  6->R2#2.t2  7->R2#3.t1  2->R2#3.t2
 *   P=10 W4 b6  #1 8v9  #6 7v10  | 1->R2#0.t1  5->R2#1.t1  4->R2#1.t2  3->R2#2.t1  6->R2#2.t2  2->R2#3.t2
 *   P=11 W4 b5  #1 8v9  #5 6v11  #6 7v10  | 1->R2#0.t1  5->R2#1.t1  4->R2#1.t2  3->R2#2.t1  2->R2#3.t2
 *   P=12 W4 b4  #1 8v9  #2 5v12  #5 6v11  #6 7v10  | 1->R2#0.t1  4->R2#1.t2  3->R2#2.t1  2->R2#3.t2
 *   P=13 W4 b3  #1 8v9  #2 5v12  #3 4v13  #5 6v11  #6 7v10  | 1->R2#0.t1  3->R2#2.t1  2->R2#3.t2
 *   P=14 W4 b2  #1 8v9  #2 5v12  #3 4v13  #4 3v14  #5 6v11  #6 7v10  | 1->R2#0.t1  2->R2#3.t2
 *   P=15 W4 b1  #1 8v9  #2 5v12  #3 4v13  #4 3v14  #5 6v11  #6 7v10  #7 2v15  | 1->R2#0.t1
 *   P=16 W4 b0  #0 1v16  #1 8v9  #2 5v12  #3 4v13  #4 3v14  #5 6v11  #6 7v10  #7 2v15
 * (generated by bracketSlotTable() below and pinned by the tests.)
 *
 * The math is unbounded in P. Display LABELS are defined only for W <= 4, which
 * is every league the DB allows today (leagues_num_participants_range caps a
 * league at 16 managers, and P <= managers).
 */

// ---------------------------------------------------------------------------
// Shape
// ---------------------------------------------------------------------------

export interface PlayoffShape {
  teams: number; // P
  weeks: number; // W = ceil(log2 P)
  byes: number; // 2^W - P, to seeds 1..byes
  bracketSize: number; // 2^W
  /** Real games per round, index 0 = round 1. Byes are not games. */
  gamesPerRound: number[];
  /** P - 1: every game eliminates exactly one team. */
  totalGames: number;
}

/** True for a usable playoff team count: an integer >= 2. */
export function isValidPlayoffTeams(p: unknown): p is number {
  return typeof p === 'number' && Number.isInteger(p) && p >= 2;
}

/** Integer ceil(log2 p) for p >= 1, exact (no floating-point log). */
function ceilLog2(p: number): number {
  let w = 0;
  while (2 ** w < p) w++;
  return w;
}

/** Derive the playoff shape from P. Throws RangeError on an invalid P: callers
 * validate first (isValidPlayoffTeams) and refuse; a bad P here is a bug. */
export function playoffShape(p: number): PlayoffShape {
  if (!isValidPlayoffTeams(p)) throw new RangeError(`invalid playoff team count: ${p}`);
  const weeks = ceilLog2(p);
  const bracketSize = 2 ** weeks;
  const byes = bracketSize - p;
  const gamesPerRound = Array.from({ length: weeks }, (_, i) =>
    i === 0 ? p - bracketSize / 2 : bracketSize / 2 ** (i + 1));
  return { teams: p, weeks, byes, bracketSize, gamesPerRound, totalGames: p - 1 };
}

// ---------------------------------------------------------------------------
// Slot placement
// ---------------------------------------------------------------------------

/** The seed on each bracket line, top to bottom, for a bracket of `size` lines
 * (a power of two >= 2). Line pair (2p, 2p+1) is round-1 position p. */
export function seedOrder(size: number): number[] {
  if (!Number.isInteger(size) || size < 2 || 2 ** ceilLog2(size) !== size) {
    throw new RangeError(`bracket size must be a power of two >= 2: ${size}`);
  }
  let order = [1, 2];
  while (order.length < size) {
    const n2 = order.length * 2;
    order = order.flatMap((s, i) => (i % 2 === 0 ? [s, n2 + 1 - s] : [n2 + 1 - s, s]));
  }
  return order;
}

/** Where one side of a game comes from. Explicit, never a NULL: a slot is
 * either a known seed (round 1, or a round-2 slot filled by a bye) or the
 * winner of one specific earlier game. */
export type SlotSource =
  | { kind: 'seed'; seed: number }
  | { kind: 'winner'; round: number; position: number };

export interface BracketGame {
  round: number; // 1..W
  position: number; // 0..(2^(W-round) - 1); round-1 positions skip byes
  team1: SlotSource;
  team2: SlotSource;
}

/**
 * Every game of the bracket (P - 1 of them), ordered by round then position.
 * In round 1 the higher seed (lower number) is team1. In later rounds team1 is
 * fed from the even-position game below it and team2 from the odd one, which is
 * exactly where nextSlot sends each winner.
 */
export function planBracket(p: number): BracketGame[] {
  const shape = playoffShape(p);
  const order = seedOrder(shape.bracketSize);
  const games: BracketGame[] = [];

  // Round 1: a real game per line pair with both seeds <= P. A pair whose
  // lower seed exceeds P is a bye for the upper seed.
  const byeSeedAt = new Map<number, number>(); // round-1 position -> bye seed
  for (let pos = 0; pos < shape.bracketSize / 2; pos++) {
    const a = order[2 * pos], b = order[2 * pos + 1];
    const hi = Math.min(a, b), lo = Math.max(a, b);
    if (lo > p) byeSeedAt.set(pos, hi);
    else games.push({ round: 1, position: pos, team1: { kind: 'seed', seed: hi }, team2: { kind: 'seed', seed: lo } });
  }

  // Later rounds: each slot is fed by one game of the previous round, or (in
  // round 2 only) directly by a bye seed.
  const source = (round: number, feederPos: number): SlotSource => {
    if (round === 2 && byeSeedAt.has(feederPos)) return { kind: 'seed', seed: byeSeedAt.get(feederPos)! };
    return { kind: 'winner', round: round - 1, position: feederPos };
  };
  for (let round = 2; round <= shape.weeks; round++) {
    for (let pos = 0; pos < 2 ** (shape.weeks - round); pos++) {
      games.push({ round, position: pos, team1: source(round, 2 * pos), team2: source(round, 2 * pos + 1) });
    }
  }
  return games;
}

/** Where the winner of (round, position) plays next, or null after the final. */
export function nextSlot(
  round: number,
  position: number,
  weeks: number,
): { round: number; position: number; slot: 'team1' | 'team2' } | null {
  if (!Number.isInteger(round) || round < 1 || round > weeks) {
    throw new RangeError(`round ${round} outside 1..${weeks}`);
  }
  if (!Number.isInteger(position) || position < 0 || position >= 2 ** (weeks - round)) {
    throw new RangeError(`position ${position} outside round ${round} of a ${weeks}-week bracket`);
  }
  if (round === weeks) return null;
  return { round: round + 1, position: Math.floor(position / 2), slot: position % 2 === 0 ? 'team1' : 'team2' };
}

/** Human-readable slot table (the one quoted in this file's header). */
export function bracketSlotTable(p: number): string {
  const shape = playoffShape(p);
  const games = planBracket(p);
  const r1 = games.filter((g) => g.round === 1).map((g) =>
    `#${g.position} ${(g.team1 as { seed: number }).seed}v${(g.team2 as { seed: number }).seed}`);
  const byes: string[] = [];
  for (const g of games.filter((g) => g.round === 2)) {
    for (const slot of ['team1', 'team2'] as const) {
      const s = g[slot];
      if (s.kind === 'seed') byes.push(`${s.seed}->R2#${g.position}.${slot === 'team1' ? 't1' : 't2'}`);
    }
  }
  return `P=${p} W${shape.weeks} b${shape.byes}  ${r1.join('  ')}${byes.length ? `  | ${byes.join('  ')}` : ''}`;
}

// ---------------------------------------------------------------------------
// Round names
// ---------------------------------------------------------------------------

/** Display names counted back from the final (Giorgio, 2026-09-29). */
const ROUND_NAMES_FROM_FINAL = ['Final', 'Semifinals', 'Quarterfinals', 'Round of 16'] as const;

/**
 * Display label per round (index 0 = round 1), or null when P is invalid or
 * the bracket is longer than the named rounds (W > 4, impossible while leagues
 * cap at 16 managers). A first round that has byes is the "Wild card" round.
 * MIRRORED byte-for-byte by the client helpers (apps/mobile/lib/playoffs.ts,
 * apps/web/src/utils/playoffs.js); apps/mobile/tests-deno/playoffs.test.ts
 * pins all three to each other.
 */
export function playoffRoundLabels(p: number): string[] | null {
  if (!isValidPlayoffTeams(p)) return null;
  const { weeks, byes } = playoffShape(p);
  if (weeks > ROUND_NAMES_FROM_FINAL.length) return null;
  const rounds = Array.from({ length: weeks }, (_, i) => ROUND_NAMES_FROM_FINAL[weeks - 1 - i] as string);
  if (byes > 0 && weeks > 1) rounds[0] = 'Wild card';
  return rounds;
}

/** The STRUCTURAL code stored in matchups.playoff_round, by distance from the
 * final. Not display copy: installed app builds and the season-completion check
 * read it. Display labels come from playoffRoundLabels. */
export type PlayoffRoundCode = 'finals' | 'semi' | 'quarter' | 'round_of_16';
const ROUND_CODES_FROM_FINAL: readonly PlayoffRoundCode[] = ['finals', 'semi', 'quarter', 'round_of_16'];

export function playoffRoundCode(round: number, weeks: number): PlayoffRoundCode {
  const fromFinal = weeks - round;
  if (!Number.isInteger(fromFinal) || round < 1 || fromFinal < 0 || fromFinal >= ROUND_CODES_FROM_FINAL.length) {
    throw new RangeError(`no round code for round ${round} of ${weeks}`);
  }
  return ROUND_CODES_FROM_FINAL[fromFinal];
}
