-- ============================================================================
-- db-snapshot.sql — capture the live-Postgres facts the repo cannot know
-- ============================================================================
-- Produces the ENTIRE contents of docs/architecture/db-snapshot.json as a
-- single value. Run it in the Supabase SQL editor (or psql) against PROD,
-- copy the single cell of output, and save it verbatim to
--   docs/architecture/db-snapshot.json
-- then run `node scripts/gen-architecture.mjs`.
--
-- This is READ-ONLY. It creates nothing, alters nothing, and touches no data
-- rows -- only catalog tables (pg_proc, pg_class, pg_policy) and cron.job.
--
-- WHY THIS FILE EXISTS
-- Three classes of fact are invisible to the filesystem and are exactly the
-- ones this repo has been bitten by:
--   1. Function EXECUTE grants. Per CLAUDE.md, `REVOKE ... FROM PUBLIC` does
--      NOT remove Supabase's default per-role anon/authenticated grants, and
--      `CREATE OR REPLACE FUNCTION` does not reset privileges. The migration
--      text therefore does NOT tell you who can call a function -- only
--      proacl does. (This is the `start_new_league_season` /
--      `join_league_by_code` class of bug.)
--   2. search_path pins (proconfig). Same reason: the live definition is the
--      LAST `CREATE OR REPLACE` to win, and there are multiply-defined
--      functions in this history.
--   3. cron.job rows. Migrations unschedule/reschedule by name inside
--      DO-blocks that swallow exceptions; the live schedule is authoritative.
--
-- SECRET SAFETY -- READ BEFORE COMMITTING THE OUTPUT
-- `cron.job.command` is captured because the job body is architecturally
-- load-bearing (which URL, which auth header, which vault secret name). Today
-- every job READS its key indirectly:
--     (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'cron_apikey')
-- which is a reference, not a value, and is safe to commit. If a job is ever
-- rescheduled with a LITERAL key inlined, that literal would land in a
-- committed file. So the query below redacts anything key-shaped before
-- output, and gen-architecture.mjs independently re-scans the snapshot and
-- REFUSES to build if a key-shaped literal survives. If you ever see
-- `[REDACTED:...]` in a command, that is not a formatting artifact -- a real
-- key was inlined in a cron job and must be rotated per CLAUDE.md.
-- ============================================================================

SELECT jsonb_pretty(jsonb_build_object(

  '_comment', 'Hand-captured from prod. Regenerate with docs/architecture/db-snapshot.sql. Not generated by gen-architecture.mjs.',
  'capturedAt', to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
  'database', current_database(),
  'postgresVersion', current_setting('server_version'),

  -- ------------------------------------------------------------------------
  -- FUNCTIONS: security_definer, EXECUTE grants (proacl), search_path pin
  -- ------------------------------------------------------------------------
  -- proacl NULL means "never explicitly GRANTed or REVOKEd" -> the built-in
  -- default applies (EXECUTE to PUBLIC for functions). It is NOT the same as
  -- "no access". The generator surfaces null proacl as `grants: "default"`
  -- and flags any SECURITY DEFINER function in that state.
  'functions', (
    SELECT coalesce(jsonb_agg(f ORDER BY f ->> 'name', f ->> 'args'), '[]'::jsonb)
    FROM (
      SELECT jsonb_build_object(
        'name',            p.proname,
        'args',            pg_get_function_identity_arguments(p.oid),
        'owner',           pg_get_userbyid(p.proowner),
        'securityDefiner', p.prosecdef,
        'volatility',      CASE p.provolatile WHEN 'i' THEN 'immutable'
                                              WHEN 's' THEN 'stable'
                                              ELSE 'volatile' END,
        'proconfig',       to_jsonb(coalesce(p.proconfig, '{}'::text[])),
        'searchPath',      (
                             SELECT split_part(cfg, '=', 2)
                             FROM unnest(coalesce(p.proconfig, '{}'::text[])) AS cfg
                             WHERE cfg LIKE 'search_path=%'
                             LIMIT 1
                           ),
        -- proacl is aclitem[]; ::text[] renders each as e.g. "anon=X/postgres".
        -- NULL is preserved as JSON null on purpose (see note above).
        'acl',             CASE WHEN p.proacl IS NULL
                                THEN 'null'::jsonb
                                ELSE to_jsonb(p.proacl::text[]) END
      ) AS f
      FROM pg_proc p
      JOIN pg_namespace n ON n.oid = p.pronamespace
      WHERE n.nspname = 'public'
        AND p.prokind = 'f'
    ) s
  ),

  -- ------------------------------------------------------------------------
  -- TABLES: RLS enabled/forced + policy names, commands, roles
  -- ------------------------------------------------------------------------
  -- Policy EXPRESSIONS are deliberately NOT captured: they are long, they
  -- churn, and the architecture map only claims "RLS is on and these are the
  -- policies". Read the migration for the predicate.
  'tables', (
    SELECT coalesce(jsonb_agg(t ORDER BY t ->> 'name'), '[]'::jsonb)
    FROM (
      SELECT jsonb_build_object(
        'name',       c.relname,
        'rlsEnabled', c.relrowsecurity,
        'rlsForced',  c.relforcerowsecurity,
        'policies',   coalesce((
          SELECT jsonb_agg(jsonb_build_object(
                   'name',       pol.polname,
                   'command',    CASE pol.polcmd
                                   WHEN 'r' THEN 'SELECT'
                                   WHEN 'a' THEN 'INSERT'
                                   WHEN 'w' THEN 'UPDATE'
                                   WHEN 'd' THEN 'DELETE'
                                   ELSE 'ALL'
                                 END,
                   'permissive', pol.polpermissive,
                   'roles',      (
                                   SELECT coalesce(jsonb_agg(
                                            CASE WHEN r = 0 THEN 'PUBLIC'
                                                 ELSE pg_get_userbyid(r) END
                                          ORDER BY r), '[]'::jsonb)
                                   FROM unnest(pol.polroles) AS r
                                 )
                 ) ORDER BY pol.polname)
          FROM pg_policy pol
          WHERE pol.polrelid = c.oid
        ), '[]'::jsonb)
      ) AS t
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = 'public'
        AND c.relkind IN ('r', 'p')   -- ordinary + partitioned tables
    ) s
  ),

  -- ------------------------------------------------------------------------
  -- CRON JOBS: the authoritative schedule + command
  -- ------------------------------------------------------------------------
  -- `command` is redacted for key-shaped literals before it leaves the DB.
  -- Patterns: Supabase publishable/secret keys (sb_*_...), JWTs (eyJ...),
  -- and Alpaca-style 20+ char uppercase-alnum tokens in quotes.
  'cronJobs', (
    SELECT coalesce(jsonb_agg(jsonb_build_object(
             'jobid',    j.jobid,
             'jobname',  j.jobname,
             'schedule', j.schedule,
             'active',   j.active,
             'database', j.database,
             'username', j.username,
             'command',  regexp_replace(
                           regexp_replace(
                             regexp_replace(
                               j.command,
                               'sb_(secret|publishable)_[A-Za-z0-9_-]{10,}',
                               '[REDACTED:sb_key]', 'g'),
                             'eyJ[A-Za-z0-9_-]{10,}[.][A-Za-z0-9_-]{10,}[.][A-Za-z0-9_-]{10,}',
                             '[REDACTED:jwt]', 'g'),
                           '''[A-Za-z0-9]{20,}''',
                           '''[REDACTED:token]''', 'g')
           ) ORDER BY j.jobname), '[]'::jsonb)
    FROM cron.job j
  )

)) AS db_snapshot;
