-- ============================================================================
-- PROMOTED from supabase/migrations/deferred/ on 2026-09-25 (was
-- deferred/20260926000001; re-timed so it sorts after the latest applied
-- migration, 20261001000000). Precondition met and verified in prod: the
-- server-side finalize path (PR #14) produced full schedules for two real test
-- drafts (test_0925 via web picks + mobile; test_09_25_v2 fully on mobile with
-- server-chosen bot picks, PR #20), and no client code writes matchups or
-- league_standings (grep of apps/, 2026-09-25).
-- ============================================================================
-- Retire the interim client INSERT policies on the schedule tables:
--   [I8] matchups_insert_members          (20260712000004) — closes F10: any league
--        member could INSERT arbitrary matchups (forged pairings / weeks / dates)
--   [I9] league_standings_insert_members  (20260712000005; PR #9's F6 re-creates
--        it with zero-valued stats — IF EXISTS covers either version)
--
-- Both existed only because schedule generation ran in the web client. It now
-- runs server-side (validate-and-record-pick -> finalize_league_draft, service
-- role, bypasses RLS), and the web writers are removed, so after this migration
-- the ONLY writers of matchups / league_standings are service-role code paths.
-- The SELECT policies (matchups_select_members, league_standings_select_members)
-- are permanent and untouched.
--
-- POST-APPLY EFFECT CHECKS (run each separately):
--   -- expect exactly one row per table, cmd = SELECT
--   SELECT tablename, policyname, cmd, roles FROM pg_policies
--   WHERE schemaname = 'public' AND tablename IN ('matchups', 'league_standings')
--   ORDER BY tablename, policyname;
--   -- negative test: run docs/security/f10-policy-drop-effect-test.sql in the
--   -- SQL editor (switches to a member's role + JWT claims the way PostgREST
--   -- does, then rolls back). Expect A and B = 42501 PASS, C = PASS.
-- ============================================================================

drop policy if exists "matchups_insert_members" on public.matchups;
drop policy if exists "league_standings_insert_members" on public.league_standings;
